Repository FppEpitech/R-Type, pull requests merged in 2024-11, with the labels that each got.

#274 REFACTOR: Replace clock by chrono
  .github/workflows/DocUpdate.yml
  .github/workflows/Linter.yml
  .github/workflows/Linux.yml
  Engine/Client/Src/ClientSceneManager/ClientSceneManager.cpp
  Engine/Client/Src/ClientSceneManager/ClientSceneManager.hpp
  Engine/Client/Src/Systems/SpriteSheetAnimation/SpriteSheetAnimationSystem.cpp
  Engine/Shared/DefaultComponents/SpriteSheetAnimation/SpriteSheetAnimationComponent.cpp
  Engine/Shared/DefaultComponents/SpriteSheetAnimation/SpriteSheetAnimationComponent.hpp
  Engine/Shared/SceneManager/ASceneManager.cpp
  Game/GameData/Entities/Mob.json
  R-TypeGame/Components/Speed/SpeedComponent.cpp
  R-TypeGame/Components/Speed/SpeedComponent.hpp
  R-TypeGame/Systems/Move/MoveEntities/MoveEntitiesSystem.cpp
  R-TypeGame/Systems/Move/MoveSystemLeft/MoveSystemLeft.cpp
  R-TypeGame/Systems/Move/MoveSystemRight/MoveSystemRight.cpp
Labels: Bug

#277 FEAT: Add player and tree assets for the new game
  Game/Assets/player.glb
  Game/Assets/tree.glb
Labels: Enhancement

#280 FEAT: Send update of game to new client
  Engine/Server/Src/GameEngine/Room/Room.cpp
  Network/ABI/ABIServer.cpp
  Network/ABI/ABIServer.hpp
Labels: Enhancement, Server, Network

#289 FEAT: Added the possibility to play in singlePlayer.
  Engine/Client/Src/Application/Application.cpp
  Engine/Shared/SceneManager/ASceneManager.cpp
  Engine/Shared/SceneManager/ASceneManager.hpp
  Engine/Shared/SceneManager/ISceneManager.hpp
  Network/ABI/ABIClient.hpp
  Network/Units/ANetworkUnit/ANetworkUnit.cpp
  Network/Units/ANetworkUnit/ANetworkUnit.hpp
  Network/Units/Client/Client.cpp
  Network/Units/INetworkUnit.hpp
  R-TypeGame/EventHandlers/CMakeLists.txt
  R-TypeGame/EventHandlers/SinglePlayer/SinglePlayerHandler.cpp
  R-TypeGame/EventHandlers/SinglePlayer/SinglePlayerHandler.hpp
  R-TypeGame/Game/GameData/Scenes/Menus/mainMenu.json
  R-TypeGame/Systems/CMakeLists.txt
  R-TypeGame/Systems/Menus/Buttons/SingleplayerButton/SingleplayerButtonInitSystem.cpp
  R-TypeGame/Systems/Menus/Buttons/SingleplayerButton/SingleplayerButtonInitSystem.hpp
  R-TypeGame/Systems/Shoot/ShootDestroySystem.cpp
  R-TypeGame/Systems/ShootMob/ShootSystem.cpp
Labels: Enhancement

#264 FEAT: Scripting
  .gitignore
  Engine/Shared/DefaultComponents/Colour/ColourComponent.hpp
  Engine/Shared/DefaultComponents/IComponent.hpp
  Engine/Shared/DefaultComponents/Position2D/Position2DComponent.hpp
  Engine/Shared/DefaultSystems/CMakeLists.txt
  Engine/Shared/DefaultSystems/LuaScript/LuaScriptSystem.cpp
  Engine/Shared/DefaultSystems/LuaScript/LuaScriptSystem.hpp
  R-TypeGame/Components/Shoot/ShootComponent.hpp
  R-TypeGame/Game/GameData/Scenes/Menus/mainMenu.json
  R-TypeGame/Game/GameData/Scripts/helloWorld.lua
  R-TypeGame/Game/GameData/Scripts/rgbColour.lua
  R-TypeGame/Game/GameData/Scripts/ySlide.lua
  vcpkg.json
Labels: Enhancement, System

#293 FEAT: Multi-thread send of messages.
  Engine/Client/Src/Application/Application.cpp
  Engine/Client/Src/Application/Application.hpp
  Engine/Server/Src/GameEngine/Application/Application.cpp
  Engine/Server/Src/GameEngine/Application/Application.hpp
  Engine/Server/Src/GameEngine/Room/Room.cpp
  Engine/Server/Src/GameEngine/Room/Room.hpp
  Network/ABI/ABINetwork.cpp
Labels: Enhancement

#297 FIX: Login event loop inf.
  R-TypeGame/EventHandlers/LoginAllowed/LoginAllowedHandler.cpp
  R-TypeGame/Game/GameData/Scenes/Menus/loginMenu.json
  R-TypeGame/Systems/CMakeLists.txt
  R-TypeGame/Systems/Menus/Buttons/LoginButton/LoginButtonInitSystem.cpp
  R-TypeGame/Systems/Menus/Buttons/LoginButton/LoginButtonInitSystem.hpp
  R-TypeGame/Systems/Menus/Login/LoginCheckSystem.cpp
  R-TypeGame/Systems/Menus/Login/LoginCheckSystem.hpp
Labels: Bug

#299 FIX: Start of single player
  R-TypeGame/Game/GameData/Scenes/Menus/mainMenu.json
Labels: Bug

#300 REFACTOR: lua scripts
  Engine/Shared/DefaultSystems/LuaScript/LuaScriptSystem.cpp
  R-TypeGame/Game/GameData/Scripts/rgbColour.lua
  tools/build-windows.bat
Labels: Enhancement

#303 FIX: load luaScriptSystem in windows
  .github/workflows/Release.yml
  Engine/Shared/DefaultSystems/CMakeLists.txt
  R-TypeGame/Game/GameData/Scenes/Menus/mainMenu.json
  R-TypeGame/Game/GameData/Scripts/rgbColour.lua
Labels: Bug

#307 FEAT: Clocked run systems and event listener in game Engines
  Engine/Client/Src/Application/Application.cpp
  Engine/Client/Src/Application/Application.hpp
  Engine/Server/Src/GameEngine/Room/Room.cpp
  Engine/Server/Src/GameEngine/Room/Room.hpp
Labels: System

#308 REFACTOR: Remove old Network folders useless since Network ABI
  Engine/Client/Src/Network/CMakeLists.txt
  Engine/Client/Src/Network/NetworkClient.cpp
  Engine/Client/Src/Network/NetworkClient.hpp
  Engine/Server/Src/Network/CMakeLists.txt
  Engine/Server/Src/Network/NetworkServer.cpp
  Engine/Server/Src/Network/NetworkServer.hpp
  Engine/Shared/CMakeLists.txt
  Engine/Shared/Network/CMakeLists.txt
  Engine/Shared/Network/Packet/CMakeLists.txt
  Engine/Shared/Network/Packet/NetworkPacket.cpp
  Engine/Shared/Network/Packet/NetworkPacket.hpp
  R-TypeGame/Game/GameData/Scenes/firstScene.json
Labels: Network

#312 FEAT: Make a 3d second game
  Engine/Client/CMakeLists.txt
  Engine/Client/Src/Application/Application.cpp
  Engine/Client/Src/Application/Application.hpp
  Engine/Client/Src/GetGraphicalLibrary/IGraphic.hpp
  Engine/Client/Src/Systems/DrawHitBoxes/DrawHitBoxesSystem.cpp
  Engine/Client/Src/Systems/DrawHitBoxes/DrawHitBoxesSystem.hpp
  Engine/Shared/DefaultComponents/CMakeLists.txt
  Engine/Shared/DefaultComponents/CanJump/CanJumpComponent.cpp
  Engine/Shared/DefaultComponents/CanJump/CanJumpComponent.hpp
  Engine/Shared/DefaultComponents/ColliderDamage/ColliderDamageComponent.cpp
  Engine/Shared/DefaultComponents/ColliderDamage/ColliderDamageComponent.hpp
  Engine/Shared/DefaultComponents/HitBox/HitBoxComponent.cpp
  Engine/Shared/DefaultComponents/HitBox/HitBoxComponent.hpp
  Engine/Shared/DefaultEventHandlers/CMakeLists.txt
  Engine/Shared/DefaultEventHandlers/DrawHitBoxes/HitBoxesDrawHandler.cpp
  Engine/Shared/DefaultEventHandlers/DrawHitBoxes/HitBoxesDrawHandler.hpp
  Engine/Shared/DefaultEventHandlers/UpdateCamera/CameraUpdateHandler.cpp
  Engine/Shared/DefaultEventHandlers/UpdateCamera/CameraUpdateHandler.hpp
  Engine/Shared/DefaultEventHandlers/UpdateHitBox/HitBoxUpdateHandler.cpp
  Engine/Shared/DefaultEventHandlers/UpdateHitBox/HitBoxUpdateHandler.hpp
  Engine/Shared/DefaultParser/ColliderDamageParser/ColliderDamageParser.cpp
  Engine/Shared/DefaultParser/ColliderDamageParser/ColliderDamageParser.hpp
  Engine/Shared/DefaultSystems/CMakeLists.txt
  Engine/Shared/DefaultSystems/Gravity/GravitySystem.cpp
  GraphicLibrary/Src/GraphicLib.cpp
  GraphicLibrary/Src/GraphicLib.hpp
  QuentinTheFarmerGame/EventHandlers/CMakeLists.txt
  QuentinTheFarmerGame/EventHandlers/CreateShoot/CreateShootHandler.cpp
  QuentinTheFarmerGame/EventHandlers/CreateShoot/CreateShootHandler.hpp
  QuentinTheFarmerGame/EventHandlers/MoveEntity/MoveEntityHandler.cpp
  QuentinTheFarmerGame/EventHandlers/PlaySounds/PlaySoundsHandler.cpp
  QuentinTheFarmerGame/EventHandlers/PlaySounds/PlaySoundsHandler.hpp
  QuentinTheFarmerGame/EventHandlers/ShootMob/ShootMobHandler.cpp
  QuentinTheFarmerGame/EventHandlers/ShootMob/ShootMobHandler.hpp
  QuentinTheFarmerGame/EventHandlers/SinglePlayer/SinglePlayerHandler.cpp
  QuentinTheFarmerGame/EventHandlers/SinglePlayer/SinglePlayerHandler.hpp
  QuentinTheFarmerGame/Game/Assets/ground.glb
  QuentinTheFarmerGame/Game/GameData/Entities/Ground.json
  QuentinTheFarmerGame/Game/GameData/Entities/PlayerOne.json
  QuentinTheFarmerGame/Game/GameData/Entities/Tree.json
  QuentinTheFarmerGame/Game/GameData/Scenes/Menus/mainMenu.json
  QuentinTheFarmerGame/Game/GameData/Scenes/firstScene.json
  QuentinTheFarmerGame/Systems/CMakeLists.txt
  QuentinTheFarmerGame/Systems/Ground/GroundInitSystem.cpp
  QuentinTheFarmerGame/Systems/Ground/GroundInitSystem.hpp
  QuentinTheFarmerGame/Systems/Menus/Buttons/SingleplayerButton/SingleplayerButtonInitSystem.cpp
  QuentinTheFarmerGame/Systems/Menus/Buttons/SingleplayerButton/SingleplayerButtonInitSystem.hpp
  QuentinTheFarmerGame/Systems/Move/JumpSystem/JumpSystem.cpp
  QuentinTheFarmerGame/Systems/Move/MoveSystemDown/MoveSystemDown.cpp
  QuentinTheFarmerGame/Systems/Move/MoveSystemLeft/MoveSystemLeft.cpp
  QuentinTheFarmerGame/Systems/Move/MoveSystemRight/MoveSystemRight.cpp
  QuentinTheFarmerGame/Systems/Move/MoveSystemUp/MoveSystemUp.cpp
  QuentinTheFarmerGame/Systems/Players/PlayerInitOneSystem.cpp
  QuentinTheFarmerGame/Systems/RestartTrees/TreesInitSystem.cpp
  QuentinTheFarmerGame/Systems/RestartTrees/TreesInitSystem.hpp
  QuentinTheFarmerGame/Systems/Trees/TreeRestartSystem.cpp
  QuentinTheFarmerGame/Systems/Trees/TreeRestartSystem.hpp
  QuentinTheFarmerGame/Systems/Trees/TreesInitSystem.cpp
  QuentinTheFarmerGame/Systems/Trees/TreesInitSystem.hpp
Labels: Enhancement, Component, System

#314 FIX: Shoot
  Engine/Client/Src/Application/Application.cpp
  Engine/Client/Src/Application/Application.hpp
  Engine/Server/Src/GameEngine/Application/Application.cpp
  Engine/Server/Src/GameEngine/Room/Room.cpp
  Engine/Shared/DefaultSystems/MoveEntities/MoveEntitiesSystem.cpp
  R-TypeGame/Systems/Move/MoveSystemDown/MoveSystemDown.cpp
  R-TypeGame/Systems/Move/MoveSystemLeft/MoveSystemLeft.cpp
  R-TypeGame/Systems/Move/MoveSystemRight/MoveSystemRight.cpp
  R-TypeGame/Systems/Move/MoveSystemUp/MoveSystemUp.cpp
Labels: Bug

#315 HOTFIX: Fix the segfault of the second game
  QuentinTheFarmerGame/Game/GameData/Scenes/firstScene.json
Labels: Bug

#316 FIX: End game
  Engine/Client/Src/Application/Application.cpp
  Engine/Server/Src/GameEngine/Room/Room.cpp
  Engine/Shared/DefaultEventHandlers/MoveEntity/MoveEntityHandler.cpp
  Engine/Shared/EventListener/EventListener.cpp
  Engine/Shared/EventListener/EventListener.hpp
  Network/ABI/ABINetwork.cpp
  Network/ABI/ABINetwork.hpp
  Network/Units/ANetworkUnit/ANetworkUnit.cpp
  Network/Units/ANetworkUnit/ANetworkUnit.hpp
  Network/Units/Client/Client.cpp
  Network/Units/INetworkUnit.hpp
  Network/Units/Server/Server.cpp
  R-TypeGame/EventHandlers/CMakeLists.txt
  R-TypeGame/EventHandlers/CreateShoot/CreateShootHandler.cpp
  R-TypeGame/EventHandlers/PlayerDeath/PlayerDeathHandler.cpp
  R-TypeGame/EventHandlers/PlayerDeath/PlayerDeathHandler.hpp
  R-TypeGame/EventHandlers/ShootMob/ShootMobHandler.cpp
  R-TypeGame/Game/GameData/Entities/PlayerFour.json
  R-TypeGame/Game/GameData/Entities/PlayerThree.json
  R-TypeGame/Game/GameData/Entities/PlayerTwo.json
  R-TypeGame/Game/GameData/Scenes/endScene.json
  R-TypeGame/Game/GameData/Scenes/firstScene.json
  R-TypeGame/Systems/CMakeLists.txt
  R-TypeGame/Systems/Hitbox/HitboxPlayerSystem.cpp
  R-TypeGame/Systems/Players/Death/PlayerDeathSystem.cpp
  R-TypeGame/Systems/Players/Death/PlayerDeathSystem.hpp
  R-TypeGame/Systems/Players/PlayerInitFourSystem.cpp
  R-TypeGame/Systems/Players/PlayerInitThreeSystem.cpp
  R-TypeGame/Systems/Players/PlayerInitTwoSystem.cpp
  R-TypeGame/Systems/Shoot/ShootDamageSystem.cpp
Labels: Bug

#317 Hotfix: Comment crash on windows
  Engine/Client/Src/Application/Application.cpp
Labels: Bug
